#ifndef VERSION_H_
#define VERSION_H_

#define RELEASE_VER_MAIN 3
#define RELEASE_VER_SUB 0
#define RELEASE_VER_FIX 0
#define RELEASE_VER_PRE_SUFFIX ""

#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)

#define RELEASE_VER_STR      \
  TOSTRING(RELEASE_VER_MAIN) \
  "." TOSTRING(RELEASE_VER_SUB) \
  "." TOSTRING(RELEASE_VER_FIX) \
  RELEASE_VER_PRE_SUFFIX

#endif  // VERSION_H_
