name: Build
on: 
  push:
    paths-ignore:
      - '*.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (SemVer)'
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: build_x86
            arch: x86
          - name: build_x64
            arch: x64
          - name: build_arm64
            arch: arm64
    name: ${{ matrix.name }}
    runs-on: windows-latest
    
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        submodules: 'true'
      
    - name: Setup VC-LTL
      run: nuget install VC-LTL
      
    - name: Setup YY-Thunks
      run: nuget install YY-Thunks

    - name: Setup Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      
    - name: Configure Xmake
      run: xmake f -a ${{ matrix.arch }}
      
    - name: Build
      run: xmake
        
    - name: Upload Separate Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setdll-${{ matrix.arch }}
        path: build/release/*

  package:
    if: github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download All Artifacts
      uses: actions/download-artifact@v4
      with:
        path: build_artifacts
    
    - name: Prepare Release Files
      run: |
        for arch in x86 x64 arm64; do
          cp injectpe.bat build_artifacts/setdll-$arch
          cp README.md build_artifacts/setdll-$arch
        done

    - name: Create Archives
      run: |
        for arch in x86 x64 arm64; do
          cd build_artifacts/setdll-$arch
          zip -r ../setdll-$arch.zip .
          cd ../..
        done

    - name: Upload Archive Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setdll-release
        path: build_artifacts/*.zip
    
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: build_artifacts/**/*
        tag_name: ${{ github.event.inputs.version }}
        name: ${{ github.event.inputs.version }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
