name: Build
on: 
  push:
    paths-ignore:
      - '*.md'
      - '.gitignore'
  pull_request:
    paths-ignore:
      - '*.md'
      - '.gitignore'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (SemVer)'
        required: true

jobs:
  build:
    strategy:
      matrix:
        include:
          - name: build_x86
            arch: x86
          - name: build_x64
            arch: x64
    name: ${{ matrix.name }}
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
      
    - name: Set up Developer Command Prompt
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: ${{ matrix.arch }}
      
    - name: Build
      run: |
        nmake clean
        nmake
        
    - name: Upload seperate artifacts
      uses: actions/upload-artifact@v4
      with:
        name: setdll-${{ matrix.arch }}
        path: Release/*.exe

  package:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      with:
        path: dist
        merge-multiple: true
    
    - name: Prepare Release Files
      run: |
        cp src/injectpe.bat dist/
        cp README.md dist/

    - name: Upload Archive Artifact
      uses: actions/upload-artifact@v4
      with:
        name: setdll-release
        path: dist
    
    - name: Create 7z Archive
      if: github.event_name == 'workflow_dispatch'
      run: |
        VERSION="${{ github.event.inputs.version }}"
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        cd dist
        7z a -mx=9 -ms=on -m0=lzma2 -mmt=on setdll-${{ github.event.inputs.version }}.7z *
        
    - name: Create Release
      if: github.event_name == 'workflow_dispatch'
      uses: softprops/action-gh-release@v2
      with:
        files: dist/setdll-${{ env.VERSION }}.7z
        tag_name: ${{ env.VERSION }}
        name: ${{ env.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
